/**
 * lib/ai-content.ts
 *
 * Utilities kept for backward compatibility and seed-time use.
 * The actual Groq AI generation is now in lib/ai-generator/:
 *   - generateMasterProject.ts  (Call 1 — per enrollment)
 *   - generateStageContent.ts   (Call 2 — per stage)
 *   - getOrGenerateStageContent.ts (enforcement mechanism)
 *   - matchResources.ts         (tag-based resource lookup)
 */

// ── Emoji stripper — used everywhere AI text is rendered ─────────────────────
export function stripEmojis(text: string): string {
  return text
    .replace(
      /[\u{1F000}-\u{1FFFF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]|[\u{FE00}-\u{FE0F}]|[\u{1F900}-\u{1F9FF}]|[\u{1FA00}-\u{1FA6F}]|[\u{1FA70}-\u{1FAFF}]/gu,
      ''
    )
    .replace(/\s{2,}/g, ' ')
    .trim();
}

// ── Static stage content — used ONLY by prisma/seed.ts ───────────────────────
// No Groq calls at seed time. Provides base taskTemplate/modelAnswer/rubric
// that is stored in the Stage table. The per-enrollment personalisation
// is handled by the lib/ai-generator/ layer at runtime.

export interface StaticStageContent {
  title: string;
  plainLanguageIntro: string;
  learningObjectives: string;
  taskTemplate: string;
  modelAnswer: string;
  rubricJson: string;
}

// ── Domain-specific stage title templates ─────────────────────────────────────
// Fixed, admin-set stage names per domain. These are NOT regenerated by Groq —
// Groq only fills in the problem-statement CONTENT within each named stage.
//
// Each array has 8 entries (for the longest 90-day/8-stage CAPSTONE track).
// Shorter tracks use entries [0..stageCount-1].
// Stage [0] = warm-up, Stage [last] = industry project capstone.
//
// To rename stages later: update this map and run the migration script at:
//   prisma/migrations/update_stage_titles.ts
// DO NOT manually edit Stage.title rows one-by-one — use the script.

const DOMAIN_STAGE_TITLES: Record<string, string[]> = {
  'ai-ml': [
    'Environment Setup & Core Fundamentals',          // Stage 1 — Warm-up
    'Model Building & Data Pipeline',                  // Stage 2 — Applied
    'Feature Engineering & Data Pipeline',             // Stage 3
    'Model Evaluation & Refinement',                   // Stage 4 / Final
    'Model Optimization & Refinement',                 // Stage 5
    'Advanced Model Refinement & Evaluation',          // Stage 6
    'Deployment Preparation & Validation',             // Stage 7
    'Model Evaluation & Refinement',                   // Stage 8 — Industry Project
  ],
  'llm-generative-ai': [
    'LLM API Setup & Prompt Fundamentals',             // Stage 1 — Warm-up
    'RAG / Agent Implementation',                      // Stage 2 — Applied
    'Vector Database & Context Integration',           // Stage 3
    'Agentic Workflow & Tool Integration',             // Stage 4
    'Prompt Evaluation & Safety Guardrails',           // Stage 5
    'RAG Optimization & Memory Management',            // Stage 6
    'System Monitoring & Evaluation',                  // Stage 7
    'Integration, Testing & Deployment',               // Stage 8 — Industry Project
  ],
  'data-science': [
    'Setup & Exploratory Data Analysis',               // Stage 1 — Warm-up
    'Model Building & Feature Engineering',            // Stage 2 — Applied
    'Feature Selection & Data Cleaning',               // Stage 3
    'Evaluation & Business Insights',                  // Stage 4
    'Advanced Predictive Modelling',                   // Stage 5
    'Model Tuning & Feature Engineering',              // Stage 6
    'Business Metrics & Reporting',                    // Stage 7
    'Evaluation & Business Insights',                  // Stage 8 — Industry Project
  ],
  'data-analysis': [
    'Data Exploration & Cleaning Setup',               // Stage 1 — Warm-up
    'Analysis & Visualization',                        // Stage 2 — Applied
    'Data Transformation & Metrics',                   // Stage 3
    'Dashboard & Business Reporting',                  // Stage 4
    'Advanced Trend Analysis',                         // Stage 5
    'Executive Visualization & Insights',              // Stage 6
    'Automated Reporting Pipelines',                   // Stage 7
    'Dashboard & Business Reporting',                  // Stage 8 — Industry Project
  ],
  'iot': [
    'Component/Simulator Setup & Sensor Basics',        // Stage 1 — Warm-up
    'Circuit Build & Sensor Integration',              // Stage 2 — Applied
    'Data Reading & Microcontroller Logic',            // Stage 3
    'Automation Logic & Working Model Demo',           // Stage 4
    'Cloud Telemetry & Sensor Integration',            // Stage 5
    'System Monitoring & Alert Logic',                 // Stage 6
    'Security & Circuit Testing',                      // Stage 7
    'Automation Logic & Working Model Demo',           // Stage 8 — Industry Project
  ],
  'fullstack-java': [
    'Environment Setup & API Fundamentals',            // Stage 1 — Warm-up
    'Database Integration & Core Features',            // Stage 2 — Applied
    'Business Logic & REST APIs',                      // Stage 3
    'Frontend Integration & Deployment',               // Stage 4
    'Authentication & Security Layer',                 // Stage 5
    'Database Optimization & Testing',                 // Stage 6
    'Continuous Delivery & Integration',               // Stage 7
    'Frontend Integration & Deployment',               // Stage 8 — Industry Project
  ],
  'erp-odoo': [
    'Odoo Environment Setup & Module Navigation',      // Stage 1 — Warm-up
    'Module Configuration & Customization',            // Stage 2 — Applied
    'Business Process Configuration',                  // Stage 3
    'Business Process Automation & Testing',           // Stage 4
    'Multi-Module Integration & Workflows',            // Stage 5
    'Custom Views & Data Security',                    // Stage 6
    'User Acceptance & System Validation',             // Stage 7
    'Business Process Automation & Testing',           // Stage 8 — Industry Project
  ],
  'data-engineering': [
    'Environment & Ingestion Setup',                   // Stage 1 — Warm-up
    'Pipeline Build & Transformation',                 // Stage 2 — Applied
    'Data Ingestion & Schema Management',              // Stage 3
    'Warehouse Load & Validation',                     // Stage 4
    'Orchestration & DAG Scheduling',                  // Stage 5
    'Streaming Pipeline & Transformation',             // Stage 6
    'Quality Checks & SLA Validation',                 // Stage 7
    'Warehouse Load & Validation',                     // Stage 8 — Industry Project
  ],
  'fullstack-python': [
    'Environment Setup & API Fundamentals',            // Stage 1 — Warm-up
    'Database Integration & Core Features',            // Stage 2 — Applied
    'Business Logic & REST Services',                  // Stage 3
    'Frontend Integration & Deployment',               // Stage 4
    'Security, Auth & Middleware',                     // Stage 5
    'Database Query Optimization',                     // Stage 6
    'API Verification & Performance Testing',          // Stage 7
    'Frontend Integration & Deployment',               // Stage 8 — Industry Project
  ],
};

// Fallback for any domain slug not in the map above
const DEFAULT_STAGE_TITLES = [
  'Environment Setup & Core Fundamentals',
  'Data Pipeline & Initial Implementation',
  'Core Logic & Feature Integration',
  'Validation, Testing & Error Handling',
  'Performance Optimization & Benchmarking',
  'Integration & API Deployment',
  'Security, Logging & Monitoring',
  'Capstone Presentation & Production Release',
];

function getStageTitleForDomain(domainSlug: string, stageNumber: number): string {
  const titles = DOMAIN_STAGE_TITLES[domainSlug] ?? DEFAULT_STAGE_TITLES;
  return titles[stageNumber - 1] ?? `Stage ${stageNumber}`;
}

export async function generateStaticStageContent(
  domainName: string,
  levelName: string,
  stageNumber: number,
  totalStages: number,
  domainSlug?: string,
): Promise<StaticStageContent> {
  const slug = domainSlug ?? domainName.toLowerCase().replace(/[\s/&()]+/g, '-');
  const title = getStageTitleForDomain(slug, stageNumber);

  const isWarmUp = stageNumber === 1;
  const isCapstone = stageNumber === totalStages && totalStages > 1;

  const roleLabel = isWarmUp ? 'warm-up' : isCapstone ? 'industry project capstone' : 'applied';

  return {
    title,
    plainLanguageIntro:
      `Welcome to Stage ${stageNumber}${isWarmUp ? ' (Warm-Up)' : isCapstone ? ' (Industry Project)' : ''} of your ${domainName} ${levelName} track. ` +
      (isWarmUp
        ? 'This first stage is designed to get you comfortable with the tools and project you will be working on throughout the track. Your personalised project scenario will appear here — take time to understand it before you begin. '
        : isCapstone
        ? 'This final stage is your industry project — a full, realistic, production-flavored version of your assigned scenario. Treat this as you would a deliverable for a real employer. '
        : 'In this stage you will apply real techniques to your ongoing project scenario. Read the task brief carefully and reference what you built in previous stages. ') +
      'Your AI-personalised task will appear below when this stage is unlocked.',
    learningObjectives:
      `Apply core ${domainName} techniques to a structured real-world problem\n` +
      'Produce clean, documented, working deliverables\n' +
      `Demonstrate ${levelName}-appropriate technical depth\n` +
      `Validate your solution against the provided acceptance criteria\n` +
      (isCapstone ? 'Deliver a production-quality, professionally documented project suitable for portfolio inclusion' : ''),
    taskTemplate:
      `TASK — Stage ${stageNumber}: ${title} [${roleLabel.toUpperCase()}]\n\n` +
      'Your personalised project scenario will appear here when you open this stage.\n\n' +
      'Deliverables (all required):\n' +
      '1. Public GitHub repository or Google Colab notebook\n' +
      '2. README explaining what you built and how to run it\n' +
      '3. Working evidence: screenshots, test output, or live URL\n' +
      '4. Short reflection (3-5 sentences)\n\n' +
      'Submit a public URL. The AI evaluator will check your link.',
    modelAnswer:
      `A strong Stage ${stageNumber} (${roleLabel}) submission demonstrates:\n\n` +
      `1. Correct implementation of the core ${title} requirement\n` +
      '2. Clean, readable code with meaningful comments\n' +
      '3. Working evidence the solution functions as specified\n' +
      '4. A README enabling someone to run the project in under 5 minutes\n' +
      (isCapstone
        ? '5. Production-quality polish: error handling, edge cases, documented tradeoffs\n6. Professional reflection on real-world constraints and design decisions'
        : '5. Genuine understanding of tradeoffs made'),
    rubricJson: JSON.stringify([
      'Submission URL is publicly accessible and contains real, non-trivial work',
      `Core ${title} requirement is correctly implemented`,
      'Code is clean and readable with meaningful comments',
      'README clearly explains the approach and how to reproduce results',
      isCapstone
        ? 'Solution meets production-quality standards: error handling, edge cases, and documented tradeoffs'
        : 'Reflection demonstrates genuine understanding of the implementation',
    ]),
  };
}

// Backward-compat alias used in seed.ts
export { generateStaticStageContent as generateStageContent };
